# Generated by Django 5.0.7 on 2024-07-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
