# Generated by Django 5.0.7 on 2024-07-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_alter_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
